version: 2.1

commands:
  print_pipeline_id:
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  print_env_var:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Print my environment variable"
          command: |
            echo $MY_ENV

  save_hello_world_output:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Add output"
          command: echo "this text file persists to the workspace" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: "Print output.txt content"
          command: "cat ~/output.txt"

  print_pipline_id_job:
    docker:
      - image: alpine:3.14
    steps:
      - print_pipeline_id

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - print_env_var
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - print_pipline_id_job
